lint:
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
    - docs/images/nf-core-rnasplice_logo_dark.png
    - assets/nf-core-rnasplice_logo_light.png
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: Ben Southgate, James Ashmore
  description: Alternative splicing analysis using RNA-seq.
  force: false
  is_nfcore: true
  name: rnasplice
  org: nf-core
  outdir: .
  version: 1.1.0dev
