---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - "bioconda::bioconductor-edger=3.36.0"
  - "conda-forge::r-statmod=1.4.36"
