# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: misopysettings
description: Generate the MISO settings file for sashimi plot visualisation
keywords:
  - miso
  - alternative splicing
  - sashimi plot
tools:
  - python:
      description: Python programming language
      homepage: https://www.python.org/
      documentation: https://docs.python.org/3/
      tool_dev_url: https://www.python.org/downloads/source/
      licence: ["Python Software Foundation License"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'miso' ]`
    - bams:
        type: file
        description: BAM files whose names are included in the MISO settings file
        pattern: "*.bam"
        ontologies:
          - edam: "http://edamontology.org/format_2572" # BAM
    - miso_data:
        type: directory
        description: MISO result directories whose names are included in the settings file
        pattern: "*"
        ontologies: []
  - fig_width:
      type: integer
      description: Width of the sashimi plot figure in inches
  - fig_height:
      type: integer
      description: Height of the sashimi plot figure in inches

output:
  miso_settings:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'miso' ]`
      - miso_settings.txt:
          type: file
          description: MISO settings file for sashimi plotting
          pattern: "miso_settings.txt"
          ontologies: []
  versions_python:
    - "versions.yml":
        type: file
        description: Versions file for python

topics:
  versions:
    - versions.yml:
        type: file
        description: Versions file for python
        pattern: "versions.yml"

authors:
  - "@valentinoruggieri"
  - "@piplus2"
maintainers:
  - "@piplus2"
